# Generated by Django 4.2.2 on 2024-04-06 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, unique=True, verbose_name='title_category')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, unique=True, verbose_name='title_department')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64, verbose_name='surname')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='patronymic')),
                ('signature', models.IntegerField(verbose_name='signature')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['surname', 'name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateh', models.DateTimeField(auto_now_add=True, verbose_name='dateh')),
                ('details', models.TextField(verbose_name='history_details')),
            ],
            options={
                'db_table': 'history',
                'ordering': ['-dateh'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, unique=True, verbose_name='title_kind')),
            ],
            options={
                'db_table': 'kind',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1, verbose_name='sex')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='iin')),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('surname', models.CharField(max_length=64, verbose_name='surname')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='patronymic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'person',
                'ordering': ['surname', 'name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, unique=True, verbose_name='title_status')),
            ],
            options={
                'db_table': 'status',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='status_title_8da31b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(verbose_name='dates')),
                ('datee', models.DateTimeField(blank=True, null=True, verbose_name='datee')),
                ('paper1', models.ImageField(upload_to='images/', verbose_name='paper')),
                ('paper2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='paper')),
                ('paper3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='paper')),
                ('paper4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='paper')),
                ('paper5', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='paper')),
                ('paper6', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='paper')),
                ('paper7', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='paper')),
                ('dates1', models.DateTimeField(blank=True, null=True, verbose_name='dates1')),
                ('dates2', models.DateTimeField(blank=True, null=True, verbose_name='dates2')),
                ('dates3', models.DateTimeField(blank=True, null=True, verbose_name='dates3')),
                ('dates4', models.DateTimeField(blank=True, null=True, verbose_name='dates4')),
                ('dates5', models.DateTimeField(blank=True, null=True, verbose_name='dates5')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_category', to='sequence.category')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_employee', to='sequence.employee')),
                ('kind1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document1_kind', to='sequence.kind')),
                ('kind2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document2_kind', to='sequence.kind')),
                ('kind3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document3_kind', to='sequence.kind')),
                ('kind4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document4_kind', to='sequence.kind')),
                ('kind5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document5_kind', to='sequence.kind')),
                ('kind6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document6_kind', to='sequence.kind')),
                ('kind7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document7_kind', to='sequence.kind')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_person', to='sequence.person')),
                ('sign1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement1_employee', to='sequence.employee')),
                ('sign2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement2_employee', to='sequence.employee')),
                ('sign3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement3_employee', to='sequence.employee')),
                ('sign4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement4_employee', to='sequence.employee')),
                ('sign5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement15employee', to='sequence.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_status', to='sequence.status')),
            ],
            options={
                'db_table': 'statement',
                'ordering': ['-dates'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateq', models.DateTimeField(auto_now_add=True, verbose_name='dateq')),
                ('details', models.TextField(verbose_name='queue_details')),
                ('dateq2', models.DateTimeField(blank=True, null=True, verbose_name='dateq2')),
                ('details2', models.TextField(verbose_name='queue2_details')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_statement', to='sequence.statement')),
            ],
            options={
                'db_table': 'queue',
                'ordering': ['dateq'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, unique=True, verbose_name='title_position')),
            ],
            options={
                'db_table': 'position',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='position_title_e0ff68_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='title_news')),
                ('details', models.TextField(verbose_name='details_news')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo_news')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kind',
            index=models.Index(fields=['title'], name='kind_title_e37f47_idx'),
        ),
        migrations.AddField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_employee', to='sequence.employee'),
        ),
        migrations.AddField(
            model_name='history',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_person', to='sequence.person'),
        ),
        migrations.AddField(
            model_name='history',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_statement', to='sequence.statement'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='sequence.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_position', to='sequence.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['title'], name='department_title_9deb55_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='category_title_f3128f_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['person'], name='statement_person__58926d_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['category'], name='statement_categor_734bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['status'], name='statement_status__19befa_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['statement'], name='queue_stateme_b00f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['dateq'], name='queue_dateq_5f048b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['surname'], name='person_surname_b68bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='person_name_b6df79_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['patronymic'], name='person_patrony_406166_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['iin'], name='person_iin_441581_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['statement'], name='history_stateme_d6d401_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['dateh'], name='history_dateh_7e792a_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['employee'], name='history_employe_b0f63a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['surname'], name='employee_surname_b85b55_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='employee_name_7aabaa_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['patronymic'], name='employee_patrony_6290e8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employee_departm_820d84_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='employee_positio_c649b1_idx'),
        ),
    ]
